# Generated by Django 5.1.dev20240308100954 on 2024-03-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field",
                    models.CharField(
                        choices=[
                            ("my_choice_one", "My choice one"),
                            ("last_choice", "Last choice"),
                        ],
                        max_length=250,
                    ),
                ),
            ],
        ),
    ]
